// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::Keystore2Properties {

std::optional<bool> keystore2_enabled();

}  // namespace android::sysprop::Keystore2Properties
