// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::HdmiProperties {

[[deprecated]] std::vector<std::optional<std::int32_t>> device_type();

enum class cec_device_types_values {
    TV,
    RECORDING_DEVICE,
    RESERVED,
    TUNER,
    PLAYBACK_DEVICE,
    AUDIO_SYSTEM,
    PURE_CEC_SWITCH,
    VIDEO_PROCESSOR,
};

std::vector<std::optional<cec_device_types_values>> cec_device_types();

std::optional<bool> set_menu_language();

}  // namespace android::sysprop::HdmiProperties
